version: '3.8'

services:
  db:
    image: postgres:16
    container_name: chat-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    build: .
#    image: rabbitmq:3-management
    container_name: chat-rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ Standard
      - "15672:15672" # Management UI
      - "61613:61613" # STOMP Plugin Port
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: